#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  workaround an iOS 17 issue that the builtin hostanme provided by
#  the iSH app no longer works.
#
#  For more details see
#  https://github.com/jaclu/AOK-Filesystem-Tools/blob/main/Docs/hostname-shortcut.md
#
#  Call this from inittab in order to have hostname setup.
#  iSH-AOK can set hostname using the built in hostname cmd, so for aok
#  kernels  the custom hostname cmd is removed if found, and hostname
#  is setup to work "as normal"
#
#  For regular iSH you need to have /usr/local/bin early in path
#  in order for the custom hostname bin to be used.
#  in bash/ash prompts you can not display hostname with the default \h
#  since it is hardcoded to use /bin/hostname and thus will display localhost
#  instead use $(/usr/local/bin/hostname -s) to make sure actual hostname
#  is used
#

log_it() {
    # if no supported loggers are found, fall back to a non-dependency solution
    f_fake_syslog=/usr/local/bin/fake_syslog
    if [ -x "$f_fake_syslog" ]; then
        "$f_fake_syslog" "set_hostname" "$*"
    else
        echo "$(date +"%Y-%m-%d %H:%M:%S") set_hostname: $*" >>/var/log/messages
    fi
}

#===============================================================
#
#   Main
#
#===============================================================

f_hostname_alt=/usr/local/bin/hostname

#  Only continue if alt hostname is available
if [ -x "$f_hostname_alt" ]; then
    #  skip extra displayal of hostname, but dont filter out errors
    "$f_hostname_alt" --update >/dev/null
elif grep -qi aok /proc/ish/version 2>/dev/null; then
    #  this can only be dont on AOK kernels
    log_it "$f_hostname_alt - not found, cant sync hostname," \
        "just setting the current /etc/hostname"
    /bin/hostname -F /etc/hostname
fi
