#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
#  Displays AOK release info
#
f_aok_fs_release="/etc/aok-fs-release"

if [ -e "$f_aok_fs_release" ]; then
    echo "[35mAOK-FS release:  $(cat "$f_aok_fs_release")[0m"
fi
