#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
#  Displays important release versions during login
#
deb_version="/etc/debian_version"
aok_release="/etc/aok-release"


if [ -e "$deb_version" ]; then
    echo "Debian release: $(cat $deb_version)"
fi

if [ -e "$aok_release" ]; then
    echo "AOK release:    $(cat /etc/aok-release)"
fi

if [ -d /proc/ish ]; then
    # Dont do this whilst chrooted in linux etc
    echo "iSH release:    $(cat /proc/ish/version)"
else
    echo "iSH release:    Can't be detected whilst chrooted"
fi
