#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Display installed versions of AOK-FS, File system being used
#  and ish-release
#

#
#  Display versions of deployed environment
#

# printf "\e[35m" # set color - magenta

if test -f /etc/alpine-release; then
    echo "Alpine release:  $(cat /etc/alpine-release)"
elif test -f /etc/devuan_version; then
    echo "Devuan version:  $(cat /etc/devuan_version)"
elif test -f /etc/debian_version; then
    echo "Debian version:  $(cat /etc/debian_version)"
else
    echo "***  Failed to detect FS  ***"
fi

ish_version="$(cat /proc/ish/version 2>/dev/null)"
[ -z "$ish_version" ] && ish_version="Cant be detected whilst chrooted"
echo "iSH release:     $ish_version"

aok_release="$(cat /etc/aok-fs-release 2>/dev/null)"
[ -z "$aok_release" ] && aok_release="Not found: /etc/aok-fs-release"
echo "AOK-FS release:  $aok_release"


# printf "\e[0m" # clear color
