#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Display installed versions of AOK-FS, File system being used
#  and ish-release
#

#
#  Display versions of deployed environment
#
if test -f /etc/alpine-release; then
    # cat /etc/motd | head -n 3
    head -n 3 </etc/motd
    echo "[0m"
elif test -f /etc/debian_version && ! test -f /etc/devuan_version; then
    /etc/update-motd.d/11-aok-release
    /etc/update-motd.d/12-deb-vers
    /etc/update-motd.d/13-ish-release
    echo
elif hostfs_is_devuan; then
    /etc/update-motd.d/11-aok-release
    /etc/update-motd.d/12-devu-vers
    /etc/update-motd.d/13-ish-release
    echo
fi
