#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

if [ -f /etc/debian_version ]; then
    echo "For iSH-Debian, you disable sshd in the file /usr/local/sbin/manual_services"
    echo "This is a bit of a hack, but at least it works for now..."
    exit 0
fi

sudo rc-service sshd stop

sudo rc-update del sshd

echo "sshd has been stopped and will not run automatically"
