#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

sudo rc-service sshd stop

sudo rc-update del sshd

echo "sshd has been stopped and will not run automatically"
