#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Switch extra locking on or off
#
version="2.0.0  2022-05-25"

prog_name=$(basename "$0")

if ! grep -qi aok /proc/ish/version 2>/dev/null; then
    echo "Not running on iSH-AOK, exiting."
    exit 1
fi

# execute again as root
if [ "$(whoami)" != "root" ]; then
    sudo "$0" "$1"
    exit 0
fi

show_status() {
    STATE="$(cat /proc/ish/defaults/enable_extralocking)"
    if [ "$STATE" = "true" ]; then
        echo "on"
    elif [ "$STATE" = "false" ]; then
        echo "off"
    fi
}

usage() {
    echo "Version:  $version"
    echo
    echo "usage: $prog_name on | off | status"
    echo
    echo "Switch extra locking on or off."
    echo "Switching it on may improve stability but impacts performance"
    echo
    printf "Current status: "
    show_status
}

case "$1" in

"" | "-h" | "--help")
    usage
    exit 0
    ;;

"on")
    echo "true" >/proc/ish/defaults/enable_extralocking
    exit 0
    ;;

"off")
    echo "false" >/proc/ish/defaults/enable_extralocking
    exit 0
    ;;

"status")
    show_status
    exit 0
    ;;

*)
    echo "ERROR: Unknown option $1"
    echo
    usage
    exit 1
    ;;

esac
