#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
# Enable sshd to run automatically
#

if [ -f /etc/alpine-release ]; then
    srvc_name="sshd"
elif [ -f /etc/debian_version ]; then
    srvc_name="ssh"
else
    echo "Unknown distro, aborting"
    exit 1
fi

#
#  The Debian iSH distro does not use DSA keys, but to keep this code
#  simple, using -A will generate all missing keys, should not be a
#  security risk, since if the config does not use all keys, they will
#  be ignored even if present, and there doesn't seem to be another
#  simple way to ensure host keys are present.
#
echo "Generating SSH host keys if not present"
sudo ssh-keygen -A

sudo rc-update add "$srvc_name"

sudo rc-service "$srvc_name" start

echo
echo "Remember to set a password for the ish user if you haven't already"
echo "Do this by typing 'passwd' and following the prompts"
echo
