#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
# Enable sshd to run automatically
#

echo

if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
    echo "Generating SSH host keys"
    sudo ssh-keygen -A
fi

if [ -f /etc/debian_version ]; then
    echo "For iSH-Debian, you enable sshd in the file /usr/local/sbin/manual_services"
    echo "This is a bit of a hack, but at least it works for now..."
    exit 0
fi

sudo rc-update add sshd

sudo rc-service sshd start

echo
echo "Remember to set a password for the ish user if you haven't already"
echo "Do this by typing 'passwd' and following the prompts"
echo
