#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
# Enable sshd to run automatically
#

if [ ! -d /proc/ish ]; then
    echo "This can only be run on iSH kernels!"
    exit 1
fi

if [ -f /etc/opt/AOK/this_fs_is_chrooted ]; then
    echo "This can't be run when chrooted!"
    exit 1
fi

if [ -f /etc/alpine-release ]; then
    srvc_name="sshd"
    if [ ! -f /usr/sbin/sshd ]; then
        echo "=== Installing openssh-server"
        sudo apk add openssh-server
    fi
elif [ -f /etc/debian_version ]; then
    srvc_name="ssh"
    if [ ! -f /usr/sbin/sshd ]; then
        echo "=== Installing openssh-server"
        sudo apt install openssh-server
    fi
else
    echo "Unknown distro, aborting"
    exit 1
fi

#  Generate ssh host keys if needed
sudo ssh-keygen -A

sudo rc-update add "$srvc_name" default

sudo rc-service "$srvc_name" start

echo
echo "Remember to set a password for the user [USERNAME] if you haven't already"
echo "sshd does not allow logins to accounts without password, even when using"
echo "pubkey."
echo "Do this by typing 'passwd [USERNAME]' (if your root) or just 'passwd' (if you are the user)"
echo " and follow the prompts"
echo

if [ -f /etc/debian_version ]; then
    echo "Debian notice: sshd should now be running, but won't show up in rc-status"
    echo "right away. After a reboot sshd will indicate run status."
fi
