#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
#
#  Restart all non-running services
#
version="0.1.0  2022-05-25"

if [ ! -d /proc/ish ]; then
    echo "This can only be run on iSH kernels!"
    exit 1
fi

prog_name=$(basename "$0")

# execute again as root
if [ "$(whoami)" != "root" ]; then
    echo "Executing as root"
    # using $0 instead of full path makes location not hardcoded
    sudo "$0"
    exit 0
fi

echo "$prog_name  $version"
echo
echo "This restarts all services not in a running state"
echo

# shellcheck disable=SC1007
current_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
"$current_dir"/do_fix_services
