#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Make it easier for people to mount their iCloud drive in iSh,
#  Also create a /iCloud/AOK directory
#
echo "When the file picker pops up please choose a "
echo "directory to mount."
echo
echo "You can optionally create a new one, or use "
echo "an existing directory."
echo
echo "This directory will be used for various things "
echo "including backups of echo your AOK files"

[ ! -d "/iCloud" ] && mkdir /iCloud

sleep 6

sudo mount -t ios NULL /iCloud
