#!/usr/bin/env bash
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

INT_IP="$(curl ifconfig.me 2>/dev/null)"

echo "Internet IP: $INT_IP"

if [ -f "/proc/ish/ips" ];
then 
    LOCAL_IP="$(cat /proc/ish/ips | grep ^en | grep -v INET6 | tr -s ' ' | cut -d ' ' -f 2)"
else
    LOCAL_IP="$(/usr/local/bin/idev_ip | cut -d: -f 2)"
fi

echo "Local IP: $LOCAL_IP"
