#!/usr/bin/env bash
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

INT_IP="$(curl ifconfig.me 2>/dev/null)"

echo "Internet IP: $INT_IP"

LOCAL_IP="$(/usr/local/bin/idev_ip | cut -d: -f 2)"

echo "Local IP: $LOCAL_IP"
