#!/bin/bash

INT_IP="$(curl ifconfig.me 2>/dev/null)"

echo "Internet IP:  $INT_IP"

if [[ -f "/proc/ish/ips" ]]; then
    OUTPUT=$(grep ^en /proc/ish/ips | grep -v INET6)
    # shellcheck disable=SC2206
    OUTPUT_ARRAY=($OUTPUT)
    LOCAL_IP=${OUTPUT_ARRAY[1]}
else
    LOCAL_IP="$(/usr/local/bin/idev_ip | cut -d: -f 2)"
fi

echo "Local IP(V4): $LOCAL_IP"

if [[ -f "/proc/ish/ips" ]]; then
    OUTPUT=$(grep ^en /proc/ish/ips | grep INET6)
    # shellcheck disable=SC2206
    OUTPUT_ARRAY=($OUTPUT)
    LOCAL_IP=${OUTPUT_ARRAY[1]}
    echo "Local IP(V6): $LOCAL_IP"
fi
