#!/bin/bash

INT_IP="$(curl ifconfig.me 2>/dev/null)"

echo "Internet IP: $INT_IP"

if [ -f "/proc/ish/ips" ]; then
    OUTPUT=$(cat /proc/ish/ips | grep ^en | grep INET6)
    OUTPUT_ARRAY=($OUTPUT)
    LOCAL_IP=${OUTPUT_ARRAY[1]}
else
    LOCAL_IP="$(/usr/local/bin/idev_ip | cut -d: -f 2)"
fi

echo "Local IP(V6): $LOCAL_IP"
