#!/bin/bash

if ! grep -qi aok /proc/ish/version 2>/dev/null; then
    echo "Not running on iSH-AOK, exiting."
    exit 1
fi

INT_IP="$(curl ifconfig.me 2>/dev/null)"

echo "Internet IP: $INT_IP"

if [[ -f "/proc/ish/ips" ]]; then
    OUTPUT=$(grep en0 /proc/ish/ips | grep -v INET6)
    OUTPUT_ARRAY=("$OUTPUT")
    LOCAL_IP=${OUTPUT_ARRAY[1]}
else
    LOCAL_IP="$(/usr/local/bin/idev_ip | cut -d: -f 2)"
fi

echo "Local IP: $LOCAL_IP"
