#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
#  Shuts dowwn iSH nodes
#
#  Using restart / stop - start
#  to ensure the process is taking place
#  Just doing start is not 100% to take effect
#  depending on service states
#
#  Optional param 1 wall message
#

def_notif=$(
    cat <<'EOF'
     *** SYSTEM SHUTDOWN NOTICE ***

This machine will be shutdown in 10 seconds!!
EOF
)
notification="${1:-$def_notif}"
uid="$(id | awk -F'[(=]' '{print $2}')"

if [ "$uid" -ne 0 ]; then
    echo "ERROR: shutdown requires root privileges!"
    exit 1
fi

if ! mount | grep -qw "/"; then
    echo "WARNING: No / mounted, this seems to be chrooted, aborting"
    exit 2
fi

if test -f /etc/alpine-release; then
    wall_cmd="/usr/local/bin/wall"
else
    #  Debians built-in wall works on iSH
    wall_cmd="/usr/bin/wall"
fi

"$wall_cmd" "$notification"


echo
echo "WARNING! Abort shut down by hitting Ctrl-C"
echo

#
#  2023 August - Doesnt seem to be the case any more
# if test -f /etc/debian_version; then
#     echo
#     echo "Be aware that if running Debian iSH-AOK will report the server has"
#     echo "crached once shutdown has happened, this is normal"
#     echo "since iSH-AOK has no clue why it terminated"
# fi

echo
sleep 10

echo "Commencing shutdown..."

if test -f /etc/alpine-release; then
    /etc/init.d/killprocs restart 2>/dev/null
else
    #
    #  Debian / Deuvan does not support restart
    #  so a stop start sequence must be done
    #
    /etc/init.d/killprocs stop
    /etc/init.d/killprocs start
fi
