#!/bin/sh

if [ ! -d /proc/ish ]; then
    echo "This can only be run on iSH kernels!"
    exit 1
fi


#
#  Ensuring jq is available
#
if ! command -v jq >/dev/null; then
    echo "Installing missing dependency jq"
    sudo apk add jq || {
        echo "ERROR: Failed to install jq"
	exit 1
    }
fi

printf "Gathering location..."
gps="$(head -n1 /dev/location | sed 's/+//g')"
lat="$(echo $gps | cut -d, -f 1)"
lon="$(echo $gps | cut -d, -f 2)"

url="https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lon}&zoom=99&format=json"
#echo "url is: $url"

printf " place name..."
# curl "$url" | python -m json.tool
location="$(curl "$url" 2> /dev/null)"

#echo "Location: $location"
#echo

printf "\n"
echo $location | jq .display_name
