#!/bin/sh
# This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Environment variables defining how this AOK-FS should be setup
#

#
# A list of variables used during build and for /usr/local/bin stuff
#

AOK_VERSION="Alpha-99"

#
#  ALPINE_VERSION defines what alpine-minirootfs will be used as a baseline
#
#  The officially supported and most tested is 3.14
#  If you try another one please report any issues at
#     https://github.com/emkey1/AOK-Filesystem-Tools/issues
#
# ALPINE_VERSION=3.13.12  # End of Alpine support 2021-11-01
ALPINE_VERSION=3.14.8   # End of Alpine support 2023-05-01
# ALPINE_VERSION=3.15.6   # End of Alpine support 2023-11-01
# ALPINE_VERSION=3.16.2   # End of Alpine support 2024-05-23



#
#  Use this if you have your own restore procedure.
#  If defined, this will be run at the end of first boot, at a time when
#  it should be a full AOK FS
#
FIRST_BOOT_ADDITIONAL_TASKS="" #"date ; echo 'one more date'; date"

#
#  The system will be initially set to this timezone
#
INITIAL_TIMEZONE="America/Los_Angeles"

#
# Alternatives are: enable disable once
#
INITIAL_LOGIN_MODE="enable"


#
#  Always installed packages
#
CORE_APKS="openssh openrc zsh bash tmux git curl openssl-dev shadow sudo busybox-extras mosh fortune elinks dcron dcron-openrc vim nano ssl_client ncftp coreutils findutils tar ncurses-dev ncurses file less sed gawk grep util-linux tzdata rsync"

#
#  For testing the deploy procedure, this is a bare minimum of what is needed.
#  It will not create a meaningful env for normal usage, just what is needed to
#  not get any errors during deploy. This only takes half the time to install,
#  its a life saver when debugging the deploy :)
#
# CORE_APKS="openssh openrc bash shadow sudo busybox-extras dcron dcron-openrc coreutils findutils tar file less sed gawk grep util-linux tzdata"

#
#  Additional packages.  These don't work with stock iSH but work with iSH-AOK
#  and will probably work with the Linux Kernel iSH
#  Will only be installed if the kernel is identified as iSH-AOK
#
AOK_APKS="htop procps strace"



#
#  Additional APK groups managed with /usr/local/bin/aok_groups
#
#  Any variable ending with _APKS in this file, will be seen as a package group
#  by aok_groups and with that tool you can add/delete groups more conveniently
#  than having to open this file and then do cut/paste repeatedly.
#
#  You can add/modify all the groups to your liking.
#

VNC_APKS='x11vnc x11vnc-doc xvfb xterm xorg-server xf86-video-dummy i3wm i3status i3lock xdpyinfo xdpyinfo-doc i3wm-doc i3lock-doc i3status-doc ttf-dejavu'

DEVEL_APKS='python3 py3-pip python3-dev build-base linux-headers cmake'
NODEJS_APKS='nodejs nodejs-dev'
BLOAT3_APKS='emacs neofetch'

DOCS_APKS='openssh-doc openrc-doc tmux-doc mandoc shadow-doc mosh-doc fortune-doc tzdata-doc elinks-doc dcron-doc vim-doc ncftp-doc coreutils-doc findutils-doc tar-doc ncurses-doc less-doc sed-doc gawk-doc grep-doc util-linux-doc tzdata-doc x11vnc-doc xdpyinfo-doc i3wm-doc i3lock-doc i3status-doc strace-doc mandoc man-pages bash-doc strace-doc procps-doc rsync-doc htop-doc'

