#!/bin/sh
# This is sourced. Fake bang-path to help editors and linters
#
# ShellCheck conditions at the top of the file are globals
# shellcheck disable=SC2034
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Environment variables defining how this AOK-FS should be setup
#

#
#  Variables used during build.
#  Recomended is to copy this file to .AOK_VARS and make changes there.
#  This file will be ignored by git, and overrides this file. It also
#  minimizes risk of temp changes to become unintentionally permanent.
#  Only when you think a change should be saved into git, put it here!
#

#
#  Label for AOK builds, is also displayed by motd to indicate what
#  AOK FS release is being used
#
AOK_VERSION="Beta-004"

#
#  If defined this will be created as a no-password sudo capable user
#
USER_NAME="ish"

#
# Shell for user USER_NAME (if defined)
#
USER_SHELL="/bin/bash"

#
#  Replaces /root and user home dir with pre-defined content, if defined
#
# HOME_DIR_USER="/iCloud/ish_config/home_user.tgz"
# HOME_DIR_ROOT="/iCloud/ish_config/home_root.tgz"

#
#  Alternatives are: enable disable once
#
INITIAL_LOGIN_MODE="enable"

#
#  Should normally not be set! If you want to hard-code timezone,
#  The FS will be setup without giving the option to select time-zone.
#  During testing its a convenient thing to set, not having to select a TZ
#  for every install.
#
# AOK_TIMEZONE="Europe/Berlin"

#
#  If you run both iSH-AOK and regular iSH on the same device
#  this setting modifies the hostname for aok kernels to have -aok suffix
#  So my iPad JacPad would be calling itself JacPad-aok if you check
#  `hostname` on iSH-AOK and JacPad if you check on regular iSH
#
# AOK_HOSTNAME_SUFFIX="Y"

#
#  If you manually want to add something to the new FS, before deploy
#  begins. Remember that from the outside, the new FS is located at
#  /tmp/AOK/FS
#  I use this when I want to simulate a mounted /iCloud env like what I
#  would have on my iPad, whilst testing the FS on a linux host chrooted
#  If the FS is being compressed its /iCloud is first cleared, so
#  anything you put in /iCloud will only be available for chrooted
#  sessions on the build host.
#
# POPULATE_FS="rsync -ah /home/jaclu/iCloud /tmp/AOK/FS"

#
#  Use this if you have your own restore procedure.
#  If defined, this will be run after deploy has completed, at a time
#  when it should be running inside a full AOK FS
#  If this is a script, it must be available with this PATH on the new
#  FS, that means it most likely needs to be in the iCloud mount.
#  This one it is better to define in .AOK_VARS
#
# FIRST_BOOT_ADDITIONAL_TASKS="/iCloud/deploy/additional-tasks"

#
#  Should normally not be changed! Enabling his will create a limited env
#  missing features and functionality!
#
#  Purpose is to speed up the deploy cycle when testing and improving
#  the build processess on slow devices, by cutting down on deploy heavy
#  usability features.
#
#  Valid settings
#  --------------
#  0 - Disabled, full deploy will happen
#  1 - all quick deploy options are active, CORE_APKS will not be installed
#  2 - CORE_APKS will be installed, all other QUICK_DEPLOY conditions will
#      be followed. Handle this in your .AOK_VARS something like this:
#
#      if [ "$QUICK_DEPLOY" -gt 1 ]; then
#          #
#          #  Minimal list that will generate a usable system depends
#          #  on how you use it
#          #
#          CORE_APKS="openrc openssh-client bash"
#      else
#          #  Normal build - Skipping fortune, some like it I don't :)
#          CORE_APKS="$(echo "$CORE_APKS" | sed 's/fortune//')"
#      fi
#
QUICK_DEPLOY=0

########################################################################
#
#                   Alpine Specific
#
########################################################################

#
#  ALPINE_VERSION defines what Alpine release will be used
#
# ALPINE_VERSION=3.15.9 # End of Alpine support 2023-11-01
ALPINE_VERSION=3.16.6 # End of Alpine support 2024-05-23
# ALPINE_VERSION=3.17.4 # End of Alpine support 2024-11-22
# ALPINE_VERSION=3.18.2 # End of Alpine support 2025-05-09
#
# 2023-07-28 edge doesn't work ATM, will investigate...
# #ALPINE_VERSION=edge # Current development tree

#
#  Use this if you want to deploy your own /etc/hosts file etc
#  If the file(-s) are relevant both for Alpine and Debian, point it to the same
#  template file.
#  Check /opt/AOK/Docs/custom_files_template.sh for notation of this file
#
# ALPINE_CUSTOM_FILES_TEMPLATE="/iCloud/ish_config/alpine_files_template.sh"

#
#  Always installed packages
#
pkgs_tools="busybox-extras coreutils util-linux sudo shadow \
    shadow-login tzdata findutils sed tar file gawk grep less git \
    sqlite fzf py3-pip ncdu"
pkgs_shells="bash zsh"
pkgs_services="openrc dcron dcron-openrc"
pkgs_net_tools="ssl_client openssh rsync curl wget elinks mosh"
pkgs_editing="vim nano"
pkgs_text_ui="ncurses newt tmux"
pkgs_other="fortune"
CORE_APKS="$pkgs_tools $pkgs_shells $pkgs_services $pkgs_net_tools \
    $pkgs_editing $pkgs_text_ui $pkgs_other"

#
#  Additional packages. These don't work with stock iSH but work with
#  iSH-AOK and will probably work with the Linux Kernel iSH
#  Will only be installed if the kernel is identified as iSH-AOK.
#  If doing a prebuild, these will be installed regardless of
#  build platform, then on first boot at dest device, they
#  will be removed if at this time the env is not iSH-AOK
#
AOK_APKS="procps nload"

#
#  Additional APK groups managed with /usr/local/bin/aok_groups
#
#  Any variable ending with _APKS in this file, will be seen as a package
#  group by aok_groups and with that tool you can add/delete groups more
#  conveniently than having to open this file and then do cut/paste
#  repeatedly.
#
#  You can add/modify all the groups to your liking.
#  Again, consider using .AOK_VARS
#
VNC_APKS="x11vnc xvfb xterm xorg-server xf86-video-dummy i3wm i3status \
    i3lock xdpyinfo xdpyinfo-doc i3wm-doc i3lock-doc i3status-doc \
    ttf-dejavu"

DEVEL_APKS="build-base linux-headers cmake automake autoconf byacc \
    ncurses-dev openssl-dev readline-dev libffi-dev openssl-dev \
    bzip2-dev zlib-dev xz-dev sqlite-dev tk-dev libevent-dev \
    ncurses-dev python3-dev"
NODEJS_APKS='nodejs nodejs-dev'
# BLOAT3_APKS='emacs neofetch'

DOCS_APKS="openssh-doc openrc-doc nload-doc procps-doc \
    tmux-doc mandoc shadow-doc mosh-doc fortune-doc tzdata-doc \
    elinks-doc dcron-doc vim-doc ncftp-doc coreutils-doc findutils-doc \
    tar-doc ncurses-doc less-doc sed-doc gawk-doc grep-doc \
    util-linux-doc tzdata-doc x11vnc-doc xdpyinfo-doc i3wm-doc \
    i3lock-doc i3status-doc strace-doc mandoc man-pages bash-doc \
    strace-doc procps-doc rsync-doc"

########################################################################
#
#                   Debian/Devuan Specific
#
########################################################################

#
#  If this type of install is selected, this tarball will be used as base image
#
DEBIAN_SRC_IMAGE="https://www.dropbox.com/scl/fi/linuf2w3ugfw3cghmi29b/Debian10-ish-base-v37.tgz?rlkey=g0inmxdv8wia8iic1fqacfhtl"
DEVUAN_SRC_IMAGE="https://www.dropbox.com/scl/fi/hk2sgmbvkfwge7ynsqnq4/Devuan_4-ish-base-v8.tgz?rlkey=cpb49k2whc2k8o2awm4ct44ww"
#
#  Use alternate malloc suggested by xloem, still in development
#
# USE_MIMALLOC="YES"

#
#  All the basics are installed, here one can add any additional
#  packages to be installed during setup
#
DEB_PKGS=""

#
#  Use this if you want to deploy your own /etc/hosts file etc
#  If the file(-s) are relevant both for Alpine and Debian, point it to the same
#  template file.
#  Check /opt/AOK/Docs/custom_files_template.sh for notation of this file
#
# DEBIAN_CUSTOM_FILES_TEMPLATE="/iCloud/ish_config/debian_files_template.sh"
