#!/bin/sh
#
# shellcheck disable=SC2154
#
# Build the custom iSH-AOK image.  Assumes we are starting with the mini root from Alpine



#  shellcheck disable=SC1007
FS_BUILD_D=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

#
#  Ensure this is run in the intended location in case this was launched from
#  somewhere else.
#
cd "$FS_BUILD_D" || exit 1



#
#  This is run chrooted inside the iSH filesystem
#

# Set some variables
# shellcheck disable=SC1091
. /AOK/BUILD_ENV

echo
echo "=====  Setting up FS (chrooted)  ====="
echo

if [ -z "$ALPINE_RELEASE" ]; then
    echo "ERROR: ALPINE_RELEASE param not supplied"
    exit 1
fi


echo "---  Initialize APK Database  ---"

# apk update
apk -U upgrade


if [ -n "$CORE_APKS" ]; then
    echo
    echo "---  Add initial packages  ---"

    # In this case we want the variable to expand into its components
    # shellcheck disable=SC2086
    apk add $CORE_APKS
fi


if [ -n "$AOK_APKS" ]; then
    echo
    echo "---  Add AOK only packages  ---"
    # In this case we want the variable to expand into its components
    # shellcheck disable=SC2086
    apk add $AOK_APKS
fi


echo "---  Replacing a few key files  ---"

ln /etc/init.d/devfs /etc/init.d/dev

# Set a hostname (Can't currently set hostname)
# cp Files/hostname /etc

# Fake interfaces file
cp /AOK/Files/interfaces /etc/network

# Move sshd to port 1022 to avoid issues
sshd_port=1022
echo "sshd listening on port: $sshd_port"
sed -i "s/.*Port .*/Port $sshd_port/" /etc/ssh/sshd_config

# /etc/init.d/networking keeps getting screwed up for unknown reasons.
# Mitigate
mkdir /root/init.d
cp /AOK/Files/init.d/* /root/init.d

# Remove extra unused vty's, make OpenRC work
cp /AOK/Files/inittab /etc

# Custom MOTD/issue
sed "s/AOK_VERSION/$AOK_VERSION/" /AOK/Files/motd > /etc/motd
sed "s/AOK_VERSION/$AOK_VERSION/" /AOK/Files/issue > /etc/issue


# Sudoers stuff, group wheel can do sudo without password
echo "activating group wheel for passwordless sudo"
sed -i "s/# %wheel ALL=(ALL) NOPASSWD.*/%wheel ALL=(ALL) NOPASSWD: ALL/" /etc/sudoers


# Root .profile.
cp /AOK/Files/profile /etc/profile

# Add some simple scripts
cp /AOK/Files/bin/* /usr/local/bin

# cron stuff
cp /AOK/Files/cron/15min/* /etc/periodic/15min
#cp Files/cron/daily/* /etc/periodic/daily
#cp Files/cron/hourly/* /etc/periodic/hourly
#cp Files/cron/monthly/* /etc/periodic/monthly
#cp Files/cron/weekly/* /etc/periodic/weekly

mkdir -p /usr/local/sbin
cp /AOK/Files/sbin/* /usr/local/sbin

# Make a link so that showip can also be 'myip'
ln /usr/local/bin/showip /usr/local/bin/myip

chmod +x /usr/local/bin/*


echo "---  Creating the ish user and group  ---"

groupadd -g 501 ish

# temp changing UID_MIN is to silence the warning:
# ish's uid 501 outside of the UID_MIN 1000 and UID_MAX 6000 range.
#  add additional groups with -G
useradd -m -s /bin/bash -u 501 -g 501 -G wheel,root,adm ish --key UID_MIN=501

# Add dot files for ish
cp /AOK/Files/bash_profile /home/ish/.bash_profile; chown ish:ish /home/ish/.bash_profile
ln -s /home/ish/.bash_profile /home/ish/.bashrc
chown ish:ish /home/ish/.bashrc
cp /AOK/Files/zshrc /home/ish/.zshrc; chown ish:ish /home/ish/.zshrc
cp /AOK/Files/vimrc /home/ish/.vimrc; chown ish:ish /home/ish/.vimrc
# Copy to root as well
cp /AOK/Files/bash_profile /root/.bash_profile
ln -s /root/.bash_profile /root/.bashrc
cp /AOK/Files/zshrc /root/.zshrc
cp /AOK/Files/vimrc /root/.vimrc

# shadow with blank ish password
sed -i "s/ish:\!:/ish::/" /etc/shadow


# Copy some documentation to the ish user home directory


echo "---  Copying Docs  ---"

mkdir /home/ish/Docs
cp -r /AOK/Docs/* /home/ish/Docs
chown -R ish:ish /home/ish/Docs


echo "---  Setting up environment  ---"


# Networking, hostname and possibly others can't start because of
# current limitations in iSH So we fake it out
rm /etc/init.d/networking
cp /AOK/Files/init.d/* /etc/init.d

# More hackery.  Initial case is the need to make pam_motd.so optional
# So that the ish user will work in Alpine 3.14
cp /AOK/Files/pam.d/* /etc/pam.d

cp /AOK/Files/tmux.conf /home/ish/.tmux.conf
chown ish:ish /home/ish/.tmux.conf
cp /AOK/Files/tmux.conf /root/.tmux.conf

# I want vim to be vi, aliasing isn't working for some reason
# /usr/local/bin is first in the path by default, so...
ln -s /usr/bin/vim /usr/local/bin/vi

ln /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
echo "$INITIAL_TIMEZONE" >  /etc/timezone

# Change roots shell
sed -i 's/\/bin\/ash$/\/bin\/bash/' /etc/passwd

# Make a directory to later mount the iCloud drive on
mkdir /iCloud

echo "$AOK_VERSION" > /etc/aok-release

echo "---  Initial login method  ---"
cp /AOK/Files/login.loop /bin
cp /AOK/Files/login.once /bin

# chmod +x /bin/login.alpine
chmod +x /bin/login.loop
chmod +x /bin/login.once

#
#  3.16 no longer has a separate login binary, it just soft links to busybox
#  and fails when running the alternate login bins. Just keeps printing
#  the login promppt in an endless loop
#
if [ -h /bin/login ]; then
    echo
    echo "WARNING: Alpine $ALPINE_RELEASE does not support changing login method"
    echo
else
    mv /bin/login /bin/login.alpine

    if ! /usr/local/bin/aok -l "$INITIAL_LOGIN_MODE"; then
        echo "ERROR: Failed to set up INITIAL_LOGIN_MODE [$INITIAL_LOGIN_MODE]"
        exit 1
    fi
fi

#
#  Extra sanity check, only continue if there is a runable /bin/login
#
if [ ! -x /bin/login ]; then
    echo "ERROR: no run-able /bin/login present!"
    exit 1
fi


echo "---  Enabling openrc  ---"

cp /AOK/Files/rc.conf /etc
mkdir /run/openrc
touch /run/openrc/softlevel

#
# Older Alpines needs to run openrc-init
#
case "$ALPINE_RELEASE" in

    "3.12" | "3.13" | "3.14" | "3.15")
        openrc-init
        ;;

    *) ;;

esac


# Set openrc boot level to be default
echo "Setting OpenRC runlevel to 'default'"
echo "default" > /run/openrc/softlevel
