
echo "--- E! /etc/zsh/zshrc (no login: C2) [$0] [$1]"
echo "       ZDOTDIR [$ZDOTDIR]"

# If ZSH startup files exist both in $HOME and XDG-based config directory,
# print a warning (but only if running as a login shell). Note that XDG-based
# config directory is used only when no ZSH startup files are found in $HOME
# (see /etc/zsh/zshenv).
if [[ -z "${ZDOTDIR-}" && -o login ]]; then
        _xdgdir=${XDG_CONFIG_HOME:-$HOME/.config}/zsh
        if _xdgrcs=("$_xdgdir"/.z{shenv,profile,shrc,login}(N)) && (( $#_xdgrcs )); then
                _homercs=("$HOME"/.z{shenv,profile,shrc,login}(N:t))
                print "Warning: Found Zsh startup files both in ~/ and ${_xdgdir/$HOME/\~}/, the latter will\n" \
                       "        be ignored (tip: move $_homercs to ${_xdgdir/$HOME/\~}/)." >&2
        fi
        unset _xdgdir _xdgrcs _homercs
fi
