#!/bin/sh
# this is sourced, shebang just to hint editors since no extension
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

# Let's set the path here since that covers both zsh and bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#  Only do the rest on fresh login, not for subshells
[ -n "$SHLVL" ] && [ "$SHLVL" -gt 1 ] && return

if [ -f "/etc/opt/AOK/show_profile_hints" ]; then
    user_id="$(id -u)"
    sshd_enabled="$(/bin/rc-status show default 2>/dev/null | grep -q " ssh")"
    echo "><> user_id [$user_id] sshd_enabled [$sshd_enabled]"

    if [ "$user_id" -ne 1 ] || [ -z "$sshd_enabled" ]; then
        echo
        echo "------------------------------------------"
        echo

        if [ -z "$sshd_enabled" ]; then
            echo "Enable sshd on port 1022: [31menable-sshd[0m"
            echo
        fi

        if [ "$user_id" -ne 0 ]; then
            echo "Use [31msudo[0m to run commands as root"
            echo
        fi

        echo "------------------------------------------"
        echo
    fi
    unser user_id
    unset sshd_enabled
fi

echo
