#!/bin/sh
#
# Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpfull_scripts
#
#  Updates apt status of a Debian based box
#

display_time_elapsed() {
    # echo "=V= Mapt display_time_elapsed($1)"
    duration="$(($(date +%s) - mapt_time_start))"
    mins="$((duration / 60))"
    seconds="$((duration - mins * 60))"

    #  Add zero prefix when < 10
    [ "$mins" -gt 0 ] && [ "$mins" -lt 10 ] && mins="0$mins"
    [ "$seconds" -lt 10 ] && seconds="0$seconds"

    echo
    echo "display_time_elapsed - Time elapsed: $mins:$seconds - $prog_name"
    echo

    unset duration
    unset mins
    unset seconds
    # echo "^^^ Mapt display_time_elapsed() - done"
}

#===============================================================
#
#   Main
#
#===============================================================
prog_name=$(basename "$0")
mapt_time_start="$(date +%s)"
[ "$1" = "no_timing" ] && mapt_no_timing=1

echo "===  Mapt - apt maintenance  ==="

if [ "$(whoami)" != "root" ]; then
    echo "***  This must be run using sudo!  ***"
    exit 1
fi

apt autoremove -y && apt autoclean && apt -y upgrade

purge_candidates="$(dpkg -l | grep '^rc' | awk '{print $2}')"
if [ -n "$purge_candidates" ]; then
    echo
    echo "---  In need of purging  ---"
    echo "$purge_candidates"
else
    echo "---  No  purges needed  ---"
fi

#
#  Check if reboot is required
#

if [ -f /var/run/reboot-required ]; then
    echo
    cat /var/run/reboot-required
fi

[ -z "$mapt_no_timing" ] && display_time_elapsed
