#!/bin/sh

#
#  Unfortunately the console session starts before the boot process has
#  completed. This means that the console will see the "old" version of
#  /etc/motd, might be mildly confusing if you have just upgraded to a
#  new Alpine release. Something like 1-2 seconds after this is displayed
#  on the console, the file is updated, so for ssh sessions, they will
#  always see the current content. If you are curious you can alwats do
#  a: cat /etc/motd
#  Otherwise just boot again, then it should have catched up.
#

#
#  Sample setup that displays release info
#

motd_file="/etc/motd"
motd_template="/etc/motd_template"
aok_release="/etc/aok-release"

echo "[35m===>  Welcome to: $(hostname)  <===" >"$motd_file"
if [ -e "$aok_release" ]; then
    echo "AOK release:    $(cat "$aok_release")" >>"$motd_file"
fi

rel="$(grep VERSION_ID /etc/os-release | cut -d'=' -f2)"

echo "Alpine release: $rel" >>"$motd_file"
if [ -d /proc/ish ]; then
    # Dont do this whilst chrooted in linux etc
    echo "iSH release:    $(cat /proc/ish/version)" >>"$motd_file"
else
    echo "iSH release:    Can't be detected whilst chrooted" >>"$motd_file"
fi

echo "[0m" >>"$motd_file"
cat "$motd_template" >>"$motd_file"
