#!/bin/sh
#
#  shellcheck disable=SC2154
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Unfortunately the console session starts before the boot process has
#  completed. This means that the console will see the "old" version of
#  /etc/motd, might be mildly confusing if you have just upgraded to a
#  new Alpine release. Something like 1-2 seconds after this is displayed
#  on the console, the file is updated, so for ssh sessions, they will
#  always see the current content. If you are curious you can alwats do
#  a: cat /etc/motd
#  Otherwise just boot again, then it should have catched up.
#

#
#  Sample setup that displays release info
#

motd_file="/etc/motd"
motd_template="/etc/motd_template"
aok_release="/etc/aok-release"
alp_rel="$(grep VERSION_ID /etc/os-release | cut -d'=' -f2)"

if [ -e "$aok_release" ]; then
    echo "[35mAOK-FS release:  $(cat "$aok_release")[0m" >"$motd_file"
fi

echo "[35mAlpine release:  $alp_rel[0m" >>"$motd_file"

if [ -d /proc/ish ]; then
    ish_rel="$(cat /proc/ish/version)"
else
    ish_rel="Can't be detected whilst chrooted"
fi
echo "[35miSH release:     $ish_rel[0m" >>"$motd_file"

cat "$motd_template" >>"$motd_file"
