#!/bin/sh
#
# Copyright (c) 2021-2023: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpfull_scripts
#
#  Updates apt status of a Debian based box
#

display_time_elapsed() {
    _dte_label="$1"

    _dte_t_in="$(($(date +%s) - t_start))"
    _dte_mins="$((_dte_t_in / 60))"
    _dte_seconds="$((_dte_t_in - _dte_mins * 60))"

    #  Add zero prefix when < 10
    [ "$_dte_mins" -gt 0 ] && [ "$_dte_mins" -lt 10 ] && _dte_mins="0$_dte_mins"
    [ "$_dte_seconds" -lt 10 ] && _dte_seconds="0$_dte_seconds"

    echo
    echo "Time elapsed: $_dte_mins:$_dte_seconds - $_dte_label"
    echo
    unset _dte_t_in
    unset _dte_label
    unset _dte_mins
    unset _dte_seconds
}


#===============================================================
#
#   Main
#
#===============================================================


t_start="$(date +%s)"

echo "Mapt - apt maintenance"

if [ "$(whoami)" != "root" ]; then
    echo "***  This must be run using sudo!  ***"
    exit 1
fi

apt autoremove -y && apt clean && apt -y upgrade

purge_candidates="$(dpkg -l | grep '^rc' | awk '{print $2}')"
if [ -n "$purge_candidates" ]; then
    echo
    echo "===  In need of purging  ==="
    echo "$purge_candidates"
    echo
else
    echo "---  No  purges needed  ---"
fi

#
#  Check if reboot is required
#

if [ -f /var/run/reboot-required ]; then
    cat /var/run/reboot-required
fi

display_time_elapsed "Mapt"
