#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
#  Fixes /dev entries in one go, suitable for cut-paste
#

log_file="/var/log/fix_dev.log"
date >>"$log_file"

msg_1() {
    (
        echo
        echo "===  $1  ==="
    ) >>"$log_file"
}

is_ish() {
    test -d /proc/ish
}

if [ "$(uname)" = "Darwin" ]; then
    echo "Don't run this on MacOS!!"
    exit 1
fi

if ! is_ish; then
    msg_1 "Not iSH kernel, skipping fix_dev"
    exit 0
fi

#  shellcheck disable=SC2154
if [ -e /etc/opt/AOK/is_chrooted ]; then
    msg_1 "Skipping fix_dev when chrooted"
    exit 0
fi

null_is_ok=0

while [ $null_is_ok -ne 1 ]; do
    echo "fixing devs" >>"$log_file"
    # parenthesis, so this can be copy pasted into a single action
    (
        rm -f /dev/null && mknod -m 666 /dev/null c 1 3
        rm -f /dev/zero && mknod -m 666 /dev/zero c 1 5
        rm -f /dev/full && mknod -m 666 /dev/full c 1 7
        rm -f /dev/random && mknod -m 666 /dev/random c 1 8
        rm -f /dev/urandom && mknod -m 666 /dev/urandom c 1 9
        rm -f /dev/tty1 && mknod -m 666 /dev/tty1 c 4 1
        rm -f /dev/tty && mknod -m 666 /dev/tty c 5 0
        rm -f /dev/console && mknod -m 666 /dev/console c 5 1
        rm -f /dev/ptmx && mknod -m 666 /dev/ptmx c 5 2
        rm -f /dev/clipboard && mknod -m 666 /dev/clipboard c 240 0
        rm -f /dev/location && mknod -m 666 /dev/location c 240 1
    )
    sleep 0.1
    ls -l /dev/null | grep -q 'crw' && null_is_ok=1
done

# The following is needed for upstream PR #1716
if [ ! -L /dev/fd ]; then
    ln -sf /proc/self/fd /dev/fd
fi

ls -l /dev/null >>"$log_file"

# Debug log
echo "[$(date)]  fix_dev" >>/var/log/debug.log
