#!/bin/sh

# should be renamed into something better such

show_msg() {
    msg="$1"

    echo "$msg"
    echo "$msg" >>"$f_login_status"
}

f_default_user="/etc/opt/AOK/default-login-username"
f_login_status="/var/log/login_status"
export LOGIN_TIMEOUT=0 # indicate that login will never timeout

show_msg ""
show_msg "$(date)"

while true; do
    current_runlevel="$(rc-status -r)"
    if [ "$current_runlevel" = "default" ]; then
        break
    fi
    show_msg "===  current runlevel is $current_runlevel"
    sleep 2
done

while true; do
    if [ -f "$f_default_user" ]; then
        def_user="-f $(cat "$f_default_user")"
    else
        def_user=""
    fi
    # /sbin/agetty -a root pts/0 xterm-256color
    show_msg "><> def_user is [$def_user]"
    /bin/login $def_user || {
        show_msg ""
        show_msg "ERROR: using def_user: [$def_user] failed!"
        show_msg "reverting to basic login"
        show_msg ""
        /bin/login
    }
    show_msg "><> login exited with: $?"

    if [ -f "$f_continous_sessions" ]; then
        show_msg "=== /bin/login terminated, will restart after sleep 3"
        sleep 3
    else
        show_msg "Will shutdown"
        /bin/sleep infinity
    fi
done

show_msg "===  Fell out of infinite agetty loop, will sleep forever"
/bin/sleep infinity
