#!/bin/sh

echo "Console will start via a getty when runlevel default has been reached."
echo "OpenRC is somewhat buggy on iSH, so occationally it fails to reach default"
echo "If no session has started after 30 seconds - try restarting the app."
echo
echo "In case no session starts, you can still login via ssh if that is enabled"
echo "and run: 'aok -c launch' This will get back to the normal console directly"
echo
echo "As a fallback, you can revert to direct console launch, by enabeling "
echo "'Revovery mode' for this app in iOS settings, then restart the app and change"
echo "'Launch cmd' into: /bin/login -f root"
echo "Finaly hit Exit top right. Next time the app starts you should get a console directly"
echo
echo

while true; do
    current_runlevel="$(rc-status -r)"
    if [ "$current_runlevel" = "default" ]; then
        break
    fi
    echo "===  current runlevel is $current_runlevel"
    sleep 2
done

while true; do
    /sbin/agetty -a root pts/0 xterm-256color
    echp "=== agetty terminated, will restart after sleep 3"
    sleep 3
done

echo "===  Fell out of infinite agetty loop, will sleep forever"
/bin/sleep infinity
