#!/bin/sh
if [ -f "/etc/opt/AOK/show_profile_hints" ]; then
    user_id="$(id -u)"
    sshd_enabled="$(/bin/rc-status show default 2>/dev/null | grep -q " ssh")"

    if [ "$user_id" -ne 1 ] || [ -z "$sshd_enabled" ]; then
        echo
        echo "------------------------------------------"
        echo

        if [ -z "$sshd_enabled" ]; then
            echo "Enable sshd on port 1022: [31menable-sshd[0m"
            echo
        fi

        if [ "$user_id" -ne 0 ]; then
            echo "Use [31msudo[0m to run commands as root"
            echo
        fi

        echo "Useful scripts are included in /usr/local/bin"
        echo

        echo "------------------------------------------"
        echo
    fi
    unset user_id
    unset sshd_enabled
fi
