
ENV="$HOME/.env_init"; export ENV

echo "--- A  /etc/zshenv [$0] [$1]"
echo "       testing with ENV [$ENV]"
echo "       ZDOTDIR [$ZDOTDIR]"

ENV="$HOME/.env_init"; export ENV
# If $ZDOTDIR is not set and none of .zshenv, .zprofile, .zshrc, .zlogin exist
# in $HOME, read ZSH startup files from $XDG_CONFIG_HOME/zsh/ instead of $HOME.
# The point is to promote XDG-based location, but don't break existing setups.

if [[ -z "${ZDOTDIR-}" ]] && _x=("$HOME"/.z{shenv,profile,shrc,login}(N)) && (( ! $#_x )); then
        ZDOTDIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh
	echo
	echo "       ZDOTDIR [$ZDOTDIR] reasigned"
fi

unset _x
