#!/bin/bash
# Do various things to make iSH more useful.  Or work around
# oddness

# First we do stuff that only needs to happen when the root image
# is booted for the first time

ID=`id -u`


if [[ -e /etc/FIRSTBOOT ]]; then
   # /dev/null gets screwed up at times.  Recreate just in case
   # the first time we boot
   sudo rm /dev/null > /tmp/profile.debug 2>&1
   sudo mknod /dev/null c 1 3 >> /tmp/profile.debug 2>&1
   sudo chmod 666 /dev/null >> /tmp/profile.debug 2>&1

   # Start a couple of services
   sudo rc-update add dcron >/dev/null 2>/dev/null
   sudo rc-update add runbg >/dev/null 2>/dev/null

   sudo rm /etc/FIRSTBOOT # Only do this stuff once, so remove the file now
fi

# Hack for Alpine 3.14.0
OS=`/bin/cat /etc/alpine-release`

# motd works for root it 3.14.0, but not anyone else for some reason.  Annoying
if [ $OS = '3.14.0' ] && [ $ID -ne 0 ]; then
    echo
    cat /etc/motd
fi

if [ $OS = '3.14.0' ]; then
    # In Alpine 3.14 services do not start up correctly.  Run script to fix 
    # that if needed
    sudo /usr/local/bin/fix_services
fi

# Let's set the path here since that covers both zsh and bash
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/games

CHECK=`/bin/rc-status 2> /dev/null | grep sshd | wc -l`

VERBOSE=0

if [ $CHECK -eq 0 ] || [ $ID -ne 0 ]; then 
   VERBOSE=1
fi

# /etc/init.d/networking keeps getting an extra } written at the end
# For some unknown reason.  Overwrite it when we login to hopefully
# mitigate that
sudo cp /root/init.d/networking /etc/init.d

# echo $CHECK $ID $VERBOSE

if [[ $VERBOSE -eq 1 ]]; then
   echo
   echo "------------------------------------------"
   echo
fi

if [[ $CHECK -eq 0 ]]; then
   echo "Enable sshd on port 1022: [31menable_sshd[0m"
   echo
fi


if [[ $ID -ne 0 ]]; then
   echo "Use [31msudo[0m to run commands as root"
   echo
fi

if [[ $VERBOSE -eq 1 ]]; then
   echo "------------------------------------------"
   echo
fi
