#!/bin/ash
# Start various things to make iSH more useful

# Start the process that marginally reduces the chances of iSH
# Getting killed while running in the background
/usr/local/bin/rbg

# /etc/init.d/networking keeps getting an extra } written at the end
# For some unknown reason.  Overwrite it when we login to hopefully
# mitigate that
sudo cp /root/init.d/networking /etc/init.d

echo
echo "-----------------------------------------------"
echo
echo "Enable sshd on port 1022: [31menable_sshd[0m"
echo
echo "Use [31msudo[0m to run commands as root"
echo
echo "-----------------------------------------------"
echo

# Let's set the path here since that covers both zsh and bash

export PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin
