#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
#
#  Hack way to enable services until a propper fix is ready
#


enable_sshd() {
    #
    #  Some error in rc setup can be worked arround with first stopping
    #  then starting ssh twice...
    #
    /etc/init.d/ssh stop
    /etc/init.d/ssh start
    /etc/init.d/ssh start
}


#===============================================================
#
#   Main
#
#===============================================================

# Uncomment to enable sshd at boot-time
# enable_sshd
