#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
#
#  This is run during boot-up, and the intended usage case is if you want to
#  update /etc/motd every time this boots. For instance if it should indicate
#  the current iSH release, if you are using TestFlight, this might be updated
#  between runs without human intervention. It could happen also with AppStore
#  but not on a near daily basis.
#  hostname might also change between boot-ups.
#

# Debug log
echo "[$(date)]  update_motd" >>/var/log/debug.log

#
#  Sample setup that displays release info
#

motd_file="/etc/motd"
motd_template="/etc/motd_template" # The iSH-AOK logo :)
aok_release="/etc/aok-release"

echo "[35m===>  Welcome to: $(hostname)  <===" >"$motd_file"
echo "Debian release: $(cat /etc/debian_version)" >>"$motd_file"

if [ -e "$aok_release" ]; then
    echo "AOK release: $(cat "$aok_release")" >>"$motd_file"
fi

if [ -d /proc/ish ]; then
    # Dont do this whilst chrooted in linux etc
    echo "iSH release: $(cat /proc/ish/version)" >>"$motd_file"
else
    echo "iSH release: Can't be detected whilst chrooted" >>"$motd_file"
fi

echo "[0m" >>"$motd_file"
cat "$motd_template" >>"$motd_file"
