#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
#
#  do_XX scripts does the actual thing for XX
#
#  This way XX can be human friendly andd give help
#  whilst do_XX just does it, so more suitable to be called
#  from oher scripts
#
#  Any service not listed as started, will be restarted.

#  Enable for debugging, to see initial boot-up status, before this check is run
# date      >  /tmp/initial-service-status
# rc-status >> /tmp/initial-service-status

rc-status  |grep -v -e started -e Runlevel: -e started | awk '{cmd="rc-service " $1 " restart" ; system(cmd)}'
