#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

if [ ! -d /opt/AOK ]; then
    echo "/opt/AOK missing, this can't continue!"
    exit 1
fi

# Read important stuff
. /opt/AOK/AOK_VARS

# execute again as root
if [ "$(whoami)" != "root" ]; then
    echo "Executing as root"
    # using $0 instead of full path makes location not hardcoded
    sudo "$0"
    exit 0
fi

if ! command -v x11vnc >/dev/null; then
    echo
    echo "Installing dependencies"
    echo
    # In this case we want the variable to split up into separate params...
    # shellcheck disable=SC2086
    apk add $VNC_APKS
fi

echo "Creating directories and writing config files"

if [ ! -e /etc/X11/xorg.conf.d ]; then
    mkdir -p /etc/X11/xorg.conf.d
fi

cat <<HERE >/etc/X11/xorg.conf.d/10-headless.conf
Section "Monitor"
        Identifier "dummy_monitor"
        HorizSync 28.0-80.0
        VertRefresh 48.0-75.0
	DisplaySize  250 174    # In millimeters, iPad gen 7 & 8
EndSection

Section "Device"
        Identifier "dummy_card"
        VideoRam 256000
        Driver "dummy"
EndSection

Section "Screen"
        Identifier "dummy_screen"
        Device "dummy_card"
        Monitor "dummy_monitor"
        SubSection "Display"
	   depth 24
	   Modes "1024x768"  # Works OK on ~10 inch iPad's
#	   Modes "1280x1024"  # Likely to work on larger iPads
	EndSubSection
EndSection
HERE

if [ ! -e /home/ish/i3logs ]; then
    mkdir /home/ish/i3logs
    chown ish.ish /home/ish/i3logs
fi

cat <<THERE >/home/ish/.xinitrc
xrdb -merge ~/.Xresources
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
exec i3 -V >> ~/i3logs/i3log-$(date +'%F-%k-%M-%S') 2>&1
THERE

chown ish.ish /home/ish/.xinitrc

cat <<EVERYWHERE >/home/ish/.Xresources
Xft.dpi: 264
xterm*VT100.Translations: #override \
    Ctrl <Key> minus: smaller-vt-font() \n\
    Ctrl <Key> plus: larger-vt-font() \n\
    Ctrl <Key> 0: set-vt-font(d)
EVERYWHERE

chown ish.ish /home/ish/.Xresources

cat <<BEATLES >/etc/X11/Xwrapper.config
allowed_users = anybody
BEATLES

echo "------------------------------------------------------"
echo "VNC has been enabled.  To start the VNC server run..."
echo "------------------------------------------------------"
echo
echo "vnc_start"
