#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

# execute again as root
if [ "$(whoami)" != "root" ]; then
    echo "Executing as root"
    # using $0 instead of full path makes location not hardcoded
    sudo "$0" "$@"
    exit 0
fi


echo "Making sure we have the latest Alpine repository updates"
apk update
echo
echo "Installing all pending updates"
apk upgrade
