#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#

# execute again as root
if [ "$(whoami)" != "root" ]; then
    echo "Executing as root"
    # using $0 instead of full path makes location not hardcoded
    sudo "$0" "$@"
    exit 0
fi

[ -z "$d_aok_etc" ] && . /opt/AOK/tools/utils.sh

msg_1 "Making sure System is fully updated"

alpine_apk_update
Mapk
