#!/bin/ash

# Check for race condition as two or even three iSH windows can launch on iPad
# at startup

# See if location services are running already
CHECK=`busybox ps -o args | grep "cat /dev/location" | wc -l`

# Only run once.  The grep causes CHECK to equal 1
if [ $CHECK -eq 1 ]; then
   cat /dev/location > /dev/null &
fi

