#!/usr/bin/env bash
# Fake bangpath to trick linters and editors
#  shellcheck disable=SC2292
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
#
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "$(id -u)" -eq 0 ]; then
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
    PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH

if [ -n "${PS1-}" ]; then
    if [ -n "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
        # The file bash.bashrc already sets the default PS1.
        # PS1='\h:\w\$ '
        if [ -f /etc/bash.bashrc ]; then
            #  shellcheck source=/dev/null
            . /etc/bash.bashrc
        fi
    else
        if [ "$(id -u)" -eq 0 ]; then
            PS1='# '
        else
            PS1='$ '
        fi
    fi
fi

if [ -d /etc/profile.d ]; then
    for i in /etc/profile.d/*.sh; do
        if [ -r "$i" ]; then
            # shellcheck source=/dev/null
            . "$i"
        fi
    done
    unset i
fi

if [ -f "/etc/opt/AOK/show_profile_hints" ]; then
    user_id="$(id -u)"
    sshd_enabled="$(/bin/rc-status show default 2>/dev/null | grep -q " ssh")"
    echo "><> user_id [$user_id] sshd_enabled [$sshd_enabled]"

    if [ "$user_id" -ne 1 ] || [-z "$sshd_enabled" ]; then
        echo
        echo "------------------------------------------"
        echo

        if [ -z "$sshd_enabled" ]; then
            echo "Enable sshd on port 1022: [31menable-sshd[0m"
            echo
        fi

        if [ "$user_id" -ne 0 ]; then
            echo "Use [31msudo[0m to run commands as root"
            echo
        fi

        echo "------------------------------------------"
        echo
    fi
    unser user_id
    unset sshd_enabled
fi

# Be sure to set the locale
# export LANG=en_US.UTF-8
