#!/bin/ash

# Check for race condition as two or even three iSH windows can launch 
# on iPad at startup

# See if locations services are running already

CHECK=`ps -o args | grep "tail -f /dev/location" | wc -l`

# Only run once.  The grep causes CHECK to equal 1
if [ $CHECK -eq 1 ]; then
   while [ $CHECK ]; do
      cat /dev/location > /dev/null &
   done
fi

